
import json
import datetime

# Load the JSON data
with open('combined_data.json', 'r') as f:
    data = json.load(f)

# Get the hundred and twentieth process (index 119)
process = data['processes'][119]

# Populate fields
process['executive_summary'] = "Crop Development in Kenya is a core function primarily handled by the Department of Crop Development within the State Department for Agriculture, under the Ministry of Agriculture and Livestock Development (MoALD). Its mandate focuses on the development, regulation, and promotion of agricultural crops, conducting research, ensuring phytosanitary services, and formulating policies to enhance national food and nutrition security, drive economic development, and improve farmer livelihoods through sustainable and productive crop production systems across the country."
process['process_overview']['process_objective'] = "To develop, regulate, and promote agricultural crops across various sub-sectors; to conduct research and development in crops, agricultural seeds, and crop genetics to enhance productivity and resilience; to ensure phytosanitary services and compliance with international standards for crop health and trade; to formulate policies on agricultural training, agricultural land resources inventory and management, agricultural mechanization, land consolidation for agricultural benefit, and agricultural insurance; to establish agricultural extension policies and service standards to disseminate knowledge to farmers; to build capacity for agricultural staff and farmers; to support the administration of irrigation schemes for enhanced crop production; to manage biosafety aspects related to genetically modified crops; and to drive crop value chains, research, and extension services to foster economic growth and food security."
process['process_overview']['policy_legal_context'].append("Crop development functions operate under the Ministry of Agriculture and Livestock Development (MoALD). Its activities are guided by national agricultural policies (e.g., National Agricultural Sector Extension Policy, National Food and Nutrition Security Policy), relevant acts (e.g., Agriculture Act, Plant Protection Act, Biosafety Act), and strategies aimed at achieving food security, sustainable agricultural development, and poverty reduction. This aligns with national goals like Vision 2030 and the Bottom-Up Economic Transformation Agenda (BETA).")
process['stakeholders'].append({"stakeholder": "Farmers (Crop Farmers)", "role": "Primary producers of crops; beneficiaries of improved varieties, technologies, and extension services", "responsibilities": "(INFERRED) Adopting improved farming methods, utilizing extension services, supplying agricultural produce."})
process['stakeholders'].append({"stakeholder": "Agricultural Research Institutions (e.g., Kenya Agricultural and Livestock Research Organization - KALRO)", "role": "Collaborators in developing improved crop varieties, disease-resistant strains, and sustainable farming practices", "responsibilities": "(INFERRED) Conducting research, developing new technologies, providing expert advice."})
process['stakeholders'].append({"stakeholder": "Agricultural Extension Officers", "role": "Frontline disseminators of knowledge and technology to farmers; implement Ministry policies at grassroots", "responsibilities": "(INFERRED) Advising farmers, providing training, linking farmers to research and markets."})
process['stakeholders'].append({"stakeholder": "Seed Companies", "role": "Partners in the development, multiplication, and distribution of quality seeds to farmers", "responsibilities": "(INFERRED) Developing and supplying quality seeds, adhering to seed certification standards."})
process['stakeholders'].append({"stakeholder": "Agricultural Input Suppliers", "role": "Provide essential inputs (fertilizers, pesticides, machinery) to farmers; regulated by Ministry standards", "responsibilities": "(INFERRED) Supplying quality inputs, adhering to regulatory standards, providing technical support."})
process['stakeholders'].append({"stakeholder": "Crop Marketers / Processors", "role": "Buyers and value-adders of agricultural produce; partners in developing efficient value chains", "responsibilities": "(INFERRED) Procuring crops, processing produce, developing market linkages, ensuring quality standards."})
process['stakeholders'].append({"stakeholder": "Ministry of Agriculture and Livestock Development", "role": "The parent Ministry providing overall policy direction, funding, and oversight for crop development", "responsibilities": "(INFERRED) Formulating agricultural policies, allocating resources, strategic guidance for crop sector."})
process['stakeholders'].append({"stakeholder": "Kenya Plant Health Inspectorate Service (KEPHIS)", "role": "Regulates plant health, seeds, and fertilizers; collaborates on phytosanitary services", "responsibilities": "(INFERRED) Ensuring plant health, regulating seed/fertilizer quality, enforcing phytosanitary standards."})
process['stakeholders'].append({"stakeholder": "National Biosafety Authority (NBA)", "role": "Regulates genetically modified organisms (GMOs) and related activities in crop production", "responsibilities": "(INFERRED) Ensuring biosafety, regulating GMO research and deployment."})
process['stakeholders'].append({"stakeholder": "County Governments", "role": "Partners in local agricultural development and extension services; implement national crop policies at county level", "responsibilities": "(INFERRED) Supporting local farmers, providing extension services, promoting county-specific crops."})
process['stakeholders'].append({"stakeholder": "National Irrigation Authority (NIA)", "role": "Collaborates on crop production in irrigated areas, especially for strategic crops like rice", "responsibilities": "(INFERRED) Developing irrigation schemes, providing water for agriculture, collaborating on crop planning."})
process['stakeholders'].append({"stakeholder": "Consumers", "role": "Ultimate beneficiaries of increased food production and stable prices; affected by crop quality and safety", "responsibilities": "(INFERRED) Purchasing food products, benefiting from national food security."})
process['stakeholders'].append({"stakeholder": "Development Partners", "role": "Provide financial and technical assistance to support crop development programs and research initiatives", "responsibilities": "(INFERRED) Funding projects, sharing expertise in agricultural best practices and food security."})

process['as_is_narrative'] = "(INFERRED) The Department of Crop Development within the Ministry of Agriculture and Livestock Development (MoALD) actively implements its mandate through a comprehensive set of interventions aimed at transforming Kenya's crop sector. It initiates the development and periodic review of national policies, strategies, and legal frameworks for various crop sub-sectors (e.g., cereals, horticulture, industrial crops), guiding sustainable production and market access. The Department implements programs for the promotion of both high-value crops and staple food crops, encouraging diversification and adoption of improved farming techniques. In collaboration with agricultural research institutions like KALRO, it coordinates and conducts research to develop improved crop varieties that are higher yielding, disease-resistant, and climate-resilient. A core function involves providing and overseeing agricultural extension services, disseminating critical knowledge, technologies, and best practices to farmers through field days, farmer training, and digital platforms. It plays a regulatory role in ensuring the quality and availability of agricultural inputs (seeds, fertilizers, pesticides) through collaboration with agencies like KEPHIS. The Department is responsible for ensuring phytosanitary standards for crop production and trade, preventing the spread of pests and diseases that could impact national food security and export markets. It actively works to develop and manage crop value chains, linking farmers to markets and promoting value addition to enhance profitability. Capacity building for agricultural staff and farmers is a continuous process through various training initiatives. The Department collaborates closely with the National Irrigation Authority (NIA) on crop production in irrigated areas and with the National Biosafety Authority (NBA) on biosafety aspects related to genetically modified crops. Furthermore, it collects, analyzes, and disseminates data on crop production, food security, and market trends to inform planning, policy decisions, and early warning systems."

# Update metadata
process['metadata']['enrichment_method'] = "web_search_and_inference"
process['metadata']['confidence_level'] = "high (mandates, functions from official Ministry website and reliable sources) / medium (inferred responsibilities, narrative)"
process['metadata']['source_urls'] = [
    "https://www.kilimo.go.ke/", # Official Ministry website
    "https://grokipedia.com/" # Provided context
]
process['metadata']['last_enriched_date'] = datetime.datetime.now().strftime("%Y-%m-%d")


# Save the updated JSON data
with open('combined_data.json', 'w') as f:
    json.dump(data, f, indent=2)

print("Hundred and twentieth process enriched and combined_data.json updated.")
