
import json
import datetime

# Load the JSON data
with open('combined_data.json', 'r') as f:
    data = json.load(f)

# Get the hundred and sixteenth process (index 115)
process = data['processes'][115]

# Populate fields
process['executive_summary'] = "The Ministry of Co-operatives And Micro, Small And Medium Enterprises (MSMEs) Development is a key government Ministry in Kenya. Its primary mandate is to formulate, adopt, and implement policy and legal frameworks for the development and growth of all co-operatives, aligning with national development policies and priorities. The Ministry is responsible for the registration, regulation, oversight, promotion, and capacity building of the cooperative sector, aiming to enhance economic growth, financial inclusion, wealth creation, and improved livelihoods for millions of Kenyans through a robust cooperative movement."
process['process_overview']['process_objective'] = "To formulate and implement policy and legal frameworks for the development and growth of all co-operatives; to register and liquidate co-operative enterprises, and establish uniform standards for their operations; to recognize county and cross-county co-operative enterprises; to regulate co-operative audit services, including social and value-for-money audits; to carry out inquiries, inspections, and investigations into co-operative affairs; to provide oversight to apex, federations, secondary, and cross-county co-operative enterprises; to promote good governance and ethics within co-operative enterprises; to promote co-operative ventures, production, marketing, and value addition; to carry out capacity building for County Governments and co-operative leaders; to develop policies related to co-operative savings, credit, and other financial services; to promote public-private partnerships and joint ventures for co-operative growth; to facilitate regional and international co-operative relations; to establish and maintain a data and information center for co-operatives and promote research and development in the sector; and to provide accessible online services such as name searches, registration of cooperative societies, cooperative audits, official searches, and registration of amendments of bylaws."
process['process_overview']['policy_legal_context'].append("Established as the Ministry of Co-operatives And Micro, Small And Medium Enterprises (MSMEs) Development. Its mandate is rooted in the Sessional Paper No. 6 of 1997 on Co-operatives and the Co-operative Societies Act, Cap 490, as well as other relevant legislation like the MSMEs Act. The Ministry aligns its activities with national development policies such as Vision 2030 and the Bottom-Up Economic Transformation Agenda (BETA), aiming for economic empowerment, social transformation, and enhanced financial inclusion through the cooperative model.")
process['stakeholders'].append({"stakeholder": "Co-operative Societies (SACCOs, Producer Co-ops, Housing Co-ops, etc.)", "role": "Primary entities regulated, promoted, and supported by the Ministry; vehicles for economic empowerment", "responsibilities": "(INFERRED) Complying with co-operative laws, providing member services, promoting good governance."})
process['stakeholders'].append({"stakeholder": "Co-operative Members", "role": "Owners and beneficiaries of co-operative enterprises; their welfare is protected by the Ministry", "responsibilities": "(INFERRED) Participating in co-operative governance, utilizing services, contributing to growth."})
process['stakeholders'].append({"stakeholder": "Ministry of Co-operatives And MSMEs Development (itself)", "role": "The central body for policy formulation, regulation, and promotion of co-operatives", "responsibilities": "(INFERRED) Providing leadership, oversight, and strategic direction."})
process['stakeholders'].append({"stakeholder": "County Governments", "role": "Partners in implementing co-operative policies and programs at the local level; responsible for certain devolved co-operative functions", "responsibilities": "(INFERRED) Supporting local co-operatives, providing extension services, promoting co-operative development."})
process['stakeholders'].append({"stakeholder": "Co-operative University of Kenya (CUK)", "role": "Provides specialized education, training, research, and consultancy services to the co-operative sector; a key partner in capacity building", "responsibilities": "(INFERRED) Developing curricula, training co-operators, conducting research."})
process['stakeholders'].append({"stakeholder": "National Treasury", "role": "Provides funding to the Ministry and oversees financial policies affecting co-operatives", "responsibilities": "(INFERRED) Allocating budgetary resources, ensuring fiscal responsibility, managing financial sector policies."})
process['stakeholders'].append({"stakeholder": "Financial Sector Regulators (e.g., Central Bank of Kenya (CBK), Sacco Societies Regulatory Authority (SASRA))", "role": "Regulate financial aspects of co-operatives (especially SACCOs); collaborate with the Ministry on prudential standards", "responsibilities": "(INFERRED) Regulating financial institutions, ensuring financial stability, consumer protection."})
process['stakeholders'].append({"stakeholder": "Co-operative Development Partners", "role": "Provide financial and technical assistance to support co-operative programs and initiatives", "responsibilities": "(INFERRED) Funding projects, sharing expertise in co-operative development and financial inclusion."})
process['stakeholders'].append({"stakeholder": "International Co-operative Organizations (e.g., International Co-operative Alliance - ICA)", "role": "Promote co-operative principles globally; collaborate with the Ministry on international best practices", "responsibilities": "(INFERRED) Setting global co-operative standards, facilitating international collaboration."})
process['stakeholders'].append({"stakeholder": "Agribusinesses", "role": "Partners in value addition and marketing for agricultural co-operatives", "responsibilities": "(INFERRED) Procuring produce from co-operatives, collaborating on value chains, promoting market access."})
process['stakeholders'].append({"stakeholder": "Small and Micro Enterprises (SMEs)", "role": "Beneficiaries of the Ministry's broader mandate encompassing MSMEs development", "responsibilities": "(INFERRED) Utilizing support programs, engaging in entrepreneurship, contributing to economic growth."})
process['stakeholders'].append({"stakeholder": "Consumers", "role": "Beneficiaries of quality products and services provided by co-operatives", "responsibilities": "(INFERRED) Purchasing co-operative products, benefiting from competitive pricing."})

process['as_is_narrative'] = "(INFERRED) The Ministry of Co-operatives And Micro, Small And Medium Enterprises (MSMEs) Development actively fulfills its mandate through a comprehensive framework of policy formulation, regulatory oversight, and promotional activities. It develops and continuously reviews policies and legal frameworks, such as the Co-operative Societies Act and its subsidiary legislations, to ensure a conducive environment for the establishment, growth, and sound governance of cooperative enterprises. The Ministry is responsible for the registration of new cooperative societies, ensuring they adhere to foundational principles, and also oversees the liquidation of non-compliant or defunct entities. It conducts regular inquiries, inspections, and investigations into the affairs of cooperative societies to monitor compliance with laws, promote good governance, and protect members' interests. A significant function involves providing technical assistance and robust capacity-building programs to cooperative enterprises, their leaders, and county governments on best practices in cooperative management, financial literacy, value addition, and marketing. The Ministry actively promotes cooperative ventures in various sectors (e.g., agriculture, housing, finance) and facilitates marketing and market linkages for cooperative products both nationally and internationally. It regulates cooperative audit services to ensure financial accountability and transparency. The Ministry is also involved in developing policies that enhance access to co-operative savings, credit, and other financial services, often in collaboration with financial sector regulators like SASRA. Furthermore, it encourages public-private partnerships, maintains a comprehensive data and information center for the cooperative sector, and provides accessible online services for cooperative registration, amendments, and audits, thereby enhancing efficiency and transparency across the cooperative movement. These efforts collectively aim to harness the socio-economic potential of co-operatives and MSMEs for national development and poverty reduction."

# Update metadata
process['metadata']['enrichment_method'] = "web_search_and_inference"
process['metadata']['confidence_level'] = "high (mandates, functions, legal basis from official website and reliable sources) / medium (inferred responsibilities, narrative)"
process['metadata']['source_urls'] = [
    "https://www.cooperativesmsme.go.ke/", # Official website
    "https://www.msea.go.ke/", # Provided context (MSMEs part of the Ministry)
    "https://developmentaid.org/", # Provided context
    "https://ushirika.go.ke/", # Provided context
    "https://ecitizen.go.ke/" # Provided context
]
process['metadata']['last_enriched_date'] = datetime.datetime.now().strftime("%Y-%m-%d")


# Save the updated JSON data
with open('combined_data.json', 'w') as f:
    json.dump(data, f, indent=2)

print("Hundred and sixteenth process enriched and combined_data.json updated.")
