
import json
import datetime

# Load the JSON data
with open('combined_data.json', 'r') as f:
    data = json.load(f)

# Get the hundred and twenty-first process (index 120)
process = data['processes'][120]

# Populate fields
process['executive_summary'] = "The State Department for Culture and Heritage in Kenya, operating under the Ministry of Sports, Culture and Heritage (or its equivalent), is tasked with the broad mandate of promoting, preserving, and developing Kenya's rich and diverse cultural heritage. Its core responsibilities include advising the government on cultural matters, setting policy standards, fostering national unity through cultural exchange, and supporting cultural industries and infrastructure development, thereby safeguarding national identity and leveraging culture for socio-economic benefit."
process['process_overview']['process_objective'] = "To promote, revitalize, and develop all facets of culture, including performing and visual arts, languages, indigenous health, oral traditions, and the creative industries; to engage in education, information dissemination, and research concerning both tangible and intangible cultural heritage; to coordinate the safeguarding of Kenya's intangible cultural heritage and promote the diversity of cultural expressions; to formulate policies for the sports, culture, and arts industries, and develop national cultural infrastructure; to coordinate all cultural activities nationwide, document national cultural inventories, and support cultural events and festivals; to build capacity for county governments and cultural organizations; to disseminate cultural information and knowledge; to promote the use of Kiswahili, sign language, and other indigenous languages in Kenya; to facilitate cultural exchange programs at local, regional, and international levels; to offer technical support for cultural development initiatives; and to register cultural groups, associations, and agencies to foster their growth and regulation."
process['process_overview']['policy_legal_context'].append("Operating under the Ministry of Sports, Culture and Heritage (or the relevant government ministry responsible for culture, arts, and heritage). Its mandate is rooted in the Constitution of Kenya (Chapter Four, Article 11 on Culture), the Cultural Heritage Act (if applicable, otherwise general heritage acts), and relevant national policies on sports, culture, and arts. The Department plays a crucial role in implementing national cultural development strategies, promoting cultural tourism, and preserving national identity and unity, aligning with national development goals like Vision 2030 for socio-cultural development.")
process['stakeholders'].append({"stakeholder": "Kenyan Citizens (General Public)", "role": "Primary beneficiaries of cultural preservation and promotion efforts; participants in cultural events", "responsibilities": "(INFERRED) Participating in cultural activities, appreciating diversity, contributing to cultural exchange."})
process['stakeholders'].append({"stakeholder": "Ethnic Communities of Kenya", "role": "Sources of diverse cultural heritage; their traditions are promoted, preserved, and developed by the Department", "responsibilities": "(INFERRED) Sharing cultural traditions, contributing to cultural diversity, collaborating on cultural events."})
process['stakeholders'].append({"stakeholder": "Artists / Cultural Practitioners (musicians, dancers, visual artists, writers)", "role": "Creators and performers of cultural expressions; beneficiaries of promotional platforms and capacity building", "responsibilities": "(INFERRED) Creating cultural content, participating in events, contributing to cultural industries."})
process['stakeholders'].append({"stakeholder": "National Museums of Kenya (NMK)", "role": "Key institution for cultural heritage preservation and documentation; collaborates closely with the Department", "responsibilities": "(INFERRED) Preserving cultural artifacts, conducting research, collaborating on exhibitions."})
process['stakeholders'].append({"stakeholder": "Kenya National Library Service (KNLS)", "role": "Preserves and disseminates cultural knowledge through literature; collaborates on cultural initiatives", "responsibilities": "(INFERRED) Archiving cultural materials, promoting reading, collaborating on cultural programs."})
process['stakeholders'].append({"stakeholder": "Kenya Film Commission (KFC)", "role": "Promotes the film industry, which is a significant cultural expression; collaborates on cultural content creation", "responsibilities": "(INFERRED) Supporting film production, promoting local content, collaborating on cultural narratives."})
process['stakeholders'].append({"stakeholder": "Kenya Cultural Centre", "role": "Venue for cultural performances and events; collaborates with the Department on cultural programming", "responsibilities": "(INFERRED) Hosting cultural events, promoting performing arts, collaborating on cultural development."})
process['stakeholders'].append({"stakeholder": "Ministry of Sports, Culture and Heritage", "role": "Parent Ministry providing policy direction, funding, and oversight to the State Department", "responsibilities": "(INFERRED) Formulating cultural policies, allocating resources, strategic guidance for cultural sector."})
process['stakeholders'].append({"stakeholder": "County Governments", "role": "Partners in implementing cultural development programs and promoting local heritage at the county level", "responsibilities": "(INFERRED) Supporting local cultural initiatives, promoting county heritage, collaborating on cultural events."})
process['stakeholders'].append({"stakeholder": "Educational Institutions", "role": "Integrate cultural education into curricula; collaborate on cultural awareness programs", "responsibilities": "(INFERRED) Providing cultural education, organizing cultural events, collaborating on outreach."})
process['stakeholders'].append({"stakeholder": "Cultural Institutions / Organizations", "role": "Collaborators in promoting specific cultural forms and heritage aspects; partners in program implementation", "responsibilities": "(INFERRED) Promoting specific cultures, collaborating on projects, advocating for cultural rights."})
process['stakeholders'].append({"stakeholder": "International Cultural Organizations (e.g., UNESCO)", "role": "Provide international frameworks, best practices, and support for cultural heritage preservation and promotion", "responsibilities": "(INFERRED) Setting global cultural standards, funding cultural projects, facilitating international cooperation."})
process['stakeholders'].append({"stakeholder": "Media Houses", "role": "Key partners in disseminating cultural information and promoting cultural events", "responsibilities": "(INFERRED) Reporting on cultural events, promoting cultural programs, educating the public."})
process['stakeholders'].append({"stakeholder": "Tourism Sector", "role": "Benefits from a vibrant cultural heritage; collaborates on cultural tourism promotion", "responsibilities": "(INFERRED) Promoting cultural tourism products, investing in heritage sites, collaborating on marketing."})
process['stakeholders'].append({"stakeholder": "Religious Organizations", "role": "Play a role in preserving certain cultural practices and traditions; collaborate on cultural dialogues", "responsibilities": "(INFERRED) Preserving religious/cultural practices, collaborating on interfaith dialogue, supporting cultural initiatives."})

process['as_is_narrative'] = "(INFERRED) The State Department for Culture and Heritage actively fulfills its mandate through a multi-faceted approach to promote, preserve, and develop Kenya's rich cultural tapestry. It is responsible for developing and reviewing national cultural policies and legal frameworks that guide the sector. The Department initiates and implements programs aimed at revitalizing traditional music, dance, performing arts, visual arts, and indigenous languages, often supporting artists and cultural groups. It engages in extensive research and documentation of both tangible (e.g., historical sites, artifacts) and intangible (e.g., oral traditions, traditional knowledge, rituals) cultural heritage assets, often in collaboration with institutions like the National Museums of Kenya and Kenya National Library Service. The Department coordinates national cultural events, festivals, and exhibitions, providing platforms for showcasing Kenya's diverse cultural expressions and fostering national unity. It provides technical and, in some cases, financial support to cultural groups, artists, and county governments for cultural development initiatives, including capacity building for cultural practitioners. Efforts are made to facilitate cultural exchange programs both domestically and internationally, promoting cross-cultural understanding. The Department actively works to integrate culture in education and national development planning, recognizing its role as a driver of sustainable development. Furthermore, it oversees the registration of cultural groups and associations to facilitate their growth and regulation, and collaborates closely with media houses to disseminate cultural information and promote cultural awareness. Through these comprehensive activities, the State Department for Culture and Heritage plays a vital role in safeguarding Kenya's cultural identity, promoting creativity, and leveraging culture for socio-economic development and national cohesion."

# Update metadata
process['metadata']['enrichment_method'] = "web_search_and_inference"
process['metadata']['confidence_level'] = "high (mandates, functions, legal basis from official government portals and reliable sources) / medium (inferred responsibilities, narrative)"
process['metadata']['source_urls'] = [
    "https://www.sportsheritage.go.ke/", # Official government portal
    "https://ecitizen.go.ke/", # Official government portal
    "https://africa2trust.com/" # Provided context
]
process['metadata']['last_enriched_date'] = datetime.datetime.now().strftime("%Y-%m-%d")


# Save the updated JSON data
with open('combined_data.json', 'w') as f:
    json.dump(data, f, indent=2)

print("Hundred and twenty-first process enriched and combined_data.json updated.")
