
import json
import datetime

# Load the JSON data
with open('combined_data.json', 'r') as f:
    data = json.load(f)

# Get the hundred and twelfth process (index 111)
process = data['processes'][111]

# Populate fields
process['executive_summary'] = "The Coast Water Works Development Agency (CWWDA) is a state corporation in Kenya, established under the Water Act of 2016 and transitioning from the Coast Water Services Board (CWSB) in May 2019. Its primary mandate is to develop and maintain sustainable water and sanitation infrastructure within the Coast region of Kenya. This includes undertaking the development, maintenance, and management of national public water works, with the aim of delivering efficient and reliable water and sanitation services to the residents of Mombasa, Kilifi, Kwale, Tana River, Lamu, and Taita Taveta counties."
process['process_overview']['process_objective'] = "To undertake the development, maintenance, and management of water works in the Coast Region; to operate water works and provide water services until such a time these responsibilities are handed over to respective counties or water service providers; to provide technical services and capacity building to County Governments; to offer reserve capacity for water services when the Water Services Regulatory Board (WASREB) orders the transfer of functions from a defaulting water services provider to another licensee; to provide technical support to the Cabinet Secretary in fulfilling their duties under the Constitution and the Water Act 2016; to own and hold water and sewerage assets and infrastructure on behalf of the National Government; to plan, develop, and expand water and sewerage infrastructure for the National Government; to assist County Governments within its jurisdiction during the transition period in contracting out water and sewerage services provision to Water Services Providers (WSPs) and monitoring these services; to ensure compliance with licensing requirements by WSPs; to assume responsibility as a Water Service Provider as a last resort; and to manage bulk water supply from various sources, including Mzima Springs, Baricho well fields, Marere Springs, Tiwi boreholes, the Hola Water supply project, and Shella wells."
process['process_overview']['policy_legal_context'].append("Established under the Water Act of 2016 and Legal Notice Number 27 of April 26, 2019, which provides the comprehensive legal framework for its establishment and functions, transitioning from the Coast Water Services Board (CWSB). CWWDA operates under the Ministry of Water & Sanitation and Irrigation and aligns its activities with national water sector reforms, policies, and the constitutional right to clean and safe water, aiming to enhance access to water and sanitation services in the coastal region in line with national development goals.")
process['stakeholders'].append({"stakeholder": "Residents / Consumers (within the Coast Region)", "role": "Primary beneficiaries of improved water and sanitation services provided by CWWDA's projects", "responsibilities": "(INFERRED) Paying for water services, conserving water, reporting service disruptions, participating in consumer feedback mechanisms."})
process['stakeholders'].append({"stakeholder": "County Governments (Mombasa, Kilifi, Kwale, Tana River, Lamu, Taita Taveta)", "role": "Partners in water and sanitation development; benefit from CWWDA's technical support and infrastructure", "responsibilities": "(INFERRED) Collaborating on water projects, providing local support, planning for water sector development, taking over water works operation."})
process['stakeholders'].append({"stakeholder": "Water Service Providers (WSPs) (e.g., Mombasa Water Supply & Sanitation Company)", "role": "Entities responsible for the retail provision of water and sanitation services; operate infrastructure developed by CWWDA", "responsibilities": "(INFERRED) Operating water works efficiently, ensuring service delivery, managing customer relations, complying with WASREB regulations."})
process['stakeholders'].append({"stakeholder": "Ministry of Water & Sanitation and Irrigation", "role": "Parent Ministry providing policy direction, funding, and oversight to CWWDA", "responsibilities": "(INFERRED) Formulating national water policies, allocating resources, strategic guidance for the water sector."})
process['stakeholders'].append({"stakeholder": "Water Services Regulatory Board (WASREB)", "role": "Regulates water services in Kenya, including setting standards and tariffs; oversees WSPs and CWWDA's interim role as WSP", "responsibilities": "(INFERRED) Setting regulatory standards, monitoring performance, issuing directives, ensuring WSP compliance."})
process['stakeholders'].append({"stakeholder": "National Treasury", "role": "Provides funding for CWWDA's projects and operations; oversees financial management of parastatals", "responsibilities": "(INFERRED) Allocating budgetary resources, ensuring financial accountability, approving project financing."})
process['stakeholders'].append({"stakeholder": "Environmental Management Agencies (e.g., NEMA)", "role": "Collaborators in ensuring environmental sustainability of water projects; ensure compliance with environmental regulations", "responsibilities": "(INFERRED) Conducting environmental impact assessments, enforcing environmental laws related to water resources and sanitation."})
process['stakeholders'].append({"stakeholder": "Local Communities", "role": "Impacted by water projects; their participation and buy-in are important for project success and sustainability", "responsibilities": "(INFERRED) Participating in project planning, protecting water sources, engaging with CWWDA on local issues."})
process['stakeholders'].append({"stakeholder": "Development Partners", "role": "Provide financial and technical assistance to support water and sanitation infrastructure development", "responsibilities": "(INFERRED) Funding projects, sharing expertise in water resource management and engineering, capacity building."})
process['stakeholders'].append({"stakeholder": "Contractors / Consultants", "role": "Engaged by CWWDA for the design, supervision, and construction of water and sanitation projects", "responsibilities": "(INFERRED) Delivering quality infrastructure, adhering to project specifications, complying with tender terms and timelines."})

process['as_is_narrative'] = "(INFERRED) The Coast Water Works Development Agency (CWWDA) actively implements its mandate by identifying, planning, and prioritizing critical water supply and sewerage projects across its designated six counties in the Coast region. Its operations involve the detailed design, procurement, and supervision of the construction of major water supply infrastructure, including the development of new water sources (dams, boreholes, water harvesting systems), construction of water treatment plants, extensive pipeline networks, and storage facilities. CWWDA also undertakes the rehabilitation, upgrading, and expansion of existing water works and sewerage systems to improve coverage, reliability, and water quality. A key function is the management of bulk water supply systems from strategic sources like Mzima Springs, Baricho well fields, and Marere Springs, ensuring that treated water is delivered to various Water Service Providers (WSPs) for retail distribution. The Agency provides crucial technical assistance and capacity building to county governments and local WSPs, empowering them to enhance their service delivery capabilities, improve operational efficiency, and comply with regulatory requirements. CWWDA ensures strict adherence to water quality standards set by WASREB and environmental regulations throughout its project lifecycle. It mobilizes financial resources for its projects from government budgetary allocations, development partners, and other funding mechanisms. Furthermore, CWWDA collaborates closely with WSPs and county governments to ensure seamless provision of water and sanitation services, working towards achieving universal access to safe and affordable water and sanitation, thereby contributing significantly to public health, economic development, and environmental sustainability in the Coast region."

# Update metadata
process['metadata']['enrichment_method'] = "web_search_and_inference"
process['metadata']['confidence_level'] = "high (mandates, functions, legal basis from official website and other reliable sources) / medium (inferred responsibilities, narrative)"
process['metadata']['source_urls'] = [
    "https://www.cwwda.go.ke/", # Official website
    "https://www.treasury.go.ke/" # Provided context
]
process['metadata']['last_enriched_date'] = datetime.datetime.now().strftime("%Y-%m-%d")


# Save the updated JSON data
with open('combined_data.json', 'w') as f:
    json.dump(data, f, indent=2)

print("Hundred and twelfth process enriched and combined_data.json updated.")
