
import json
import datetime

# Load the JSON data
with open('combined_data.json', 'r') as f:
    data = json.load(f)

# Get the hundred and fourth process (index 103)
process = data['processes'][103]

# Populate fields
process['executive_summary'] = "The Centre for Mathematics, Science and Technology Education in Africa (CEMASTEA) is a State Corporation under the Ministry of Education in Kenya, transformed in 2022. Its principal mandate is to provide continuous professional development for teachers in Science, Technology, Engineering, and Mathematics (STEM) education, not only in Kenya but across Africa. CEMASTEA aims to enhance the quality of STEM education, conduct research to inform pedagogical practices and policy, and foster local and international collaborations to promote national and regional development through a skilled human resource base."
process['process_overview']['process_objective'] = "To provide continuous professional development (CPD) for teachers in Science, Technology, Engineering, and Mathematics (STEM) education, aligning with policies set by the Ministry of Education, the Teachers Service Commission (TSC), and other relevant stakeholders; to conduct research to inform Teacher Professional Development programs, internal quality assurance processes, and policy development; to organize and host seminars, workshops, conferences, and symposia related to STEM education and teacher capacity development; to publish and distribute information and research findings concerning STEM education and teacher capacity development; to offer advisory and consultancy services in the field of STEM education and teacher capacity development; to foster local and international partnerships and collaborations with government agencies, institutions, and organizations interested in STEM education; to serve as the Secretariat for the Strengthening of Mathematics and Science Education in Africa (SMASE-Africa) Network and ADEA's Inter-Country Quality Node on Mathematics and Science Education (ICQN-MSE); to support the implementation of STEM initiatives across Africa; to contribute to the development and review of mathematics, science, and technology curricula; to build the capacity of educators and administrators in STEM subjects; and to advocate for the significance of STEM education to promote national and regional development."
process['process_overview']['policy_legal_context'].append("CEMASTEA was transformed into a State Corporation under the Ministry of Education in 2022, with its specific mandate focusing on training and research in STEM education. It operates under the Ministry of Education and aligns its activities with national education policies, curriculum reforms (e.g., the Competency-Based Curriculum - CBC), and regional educational development goals. Its functions are guided by the Kenya Education Act and other relevant statutes concerning teacher professional development and educational research.")
process['stakeholders'].append({"stakeholder": "Teachers (Primary and Secondary School STEM Teachers)", "role": "Primary beneficiaries of CEMASTEA's CPD programs; implement improved pedagogical practices in classrooms", "responsibilities": "(INFERRED) Participating in training, applying learned methodologies, contributing to improved student performance."})
process['stakeholders'].append({"stakeholder": "Ministry of Education (Kenya)", "role": "Parent Ministry providing policy direction, funding, and oversight to CEMASTEA", "responsibilities": "(INFERRED) Formulating education policies, allocating resources, strategic guidance for STEM education."})
process['stakeholders'].append({"stakeholder": "Teachers Service Commission (TSC)", "role": "Employer of public school teachers; collaborates with CEMASTEA on teacher professional development programs", "responsibilities": "(INFERRED) Setting teacher professional standards, promoting CPD, deploying trained teachers."})
process['stakeholders'].append({"stakeholder": "Kenya Institute of Curriculum Development (KICD)", "role": "Develops and reviews the national curriculum; collaborates with CEMASTEA on curriculum implementation strategies", "responsibilities": "(INFERRED) Developing STEM curricula, providing educational materials, advising on implementation."})
process['stakeholders'].append({"stakeholder": "Kenya National Examinations Council (KNEC)", "role": "Administers national examinations; CEMASTEA's work impacts student performance in STEM subjects", "responsibilities": "(INFERRED) Setting examination standards, evaluating student performance in STEM subjects."})
process['stakeholders'].append({"stakeholder": "Educational Institutions (Schools, Colleges, Universities)", "role": "Provide platforms for STEM education; teachers from these institutions benefit from CEMASTEA's training", "responsibilities": "(INFERRED) Implementing STEM curricula, hosting training, collaborating on STEM initiatives."})
process['stakeholders'].append({"stakeholder": "SMASE-Africa Network", "role": "Regional network of STEM education centers; CEMASTEA serves as its Secretariat", "responsibilities": "(INFERRED) Coordinating regional STEM initiatives, sharing best practices, fostering collaboration."})
process['stakeholders'].append({"stakeholder": "ADEA's ICQN-MSE Network", "role": "Inter-Country Quality Node on Mathematics and Science Education; CEMASTEA serves as its Secretariat", "responsibilities": "(INFERRED) Coordinating inter-country quality initiatives, sharing knowledge, promoting educational excellence."})
process['stakeholders'].append({"stakeholder": "Curriculum Developers", "role": "Professionals involved in designing and revising educational curricula; collaborate with CEMASTEA on STEM content", "responsibilities": "(INFERRED) Developing relevant curricula, integrating CEMASTEA's research findings."})
process['stakeholders'].append({"stakeholder": "Educational Researchers", "role": "Conduct studies on educational practices; collaborate with CEMASTEA on research projects", "responsibilities": "(INFERRED) Conducting research, providing expert insights, collaborating on educational studies."})
process['stakeholders'].append({"stakeholder": "Local and International Partners (NGOs, Foundations)", "role": "Provide financial and technical support for CEMASTEA's programs and STEM initiatives", "responsibilities": "(INFERRED) Funding projects, sharing expertise, supporting capacity building."})
process['stakeholders'].append({"stakeholder": "African Governments (for STEM initiatives)", "role": "Beneficiaries of CEMASTEA's regional leadership in STEM education development", "responsibilities": "(INFERRED) Supporting STEM education, collaborating on regional initiatives, implementing CEMASTEA's recommendations."})
process['stakeholders'].append({"stakeholder": "Students (beneficiaries of improved STEM education)", "role": "Ultimate beneficiaries of enhanced STEM teaching and learning in schools", "responsibilities": "(INFERRED) Engaging in learning, pursuing STEM careers, contributing to national development."})

process['as_is_narrative'] = "(INFERRED) CEMASTEA actively fulfills its mandate by designing, developing, and delivering specialized continuous professional development (CPD) programs specifically tailored for mathematics, science, and technology teachers at both primary and secondary school levels. These programs utilize innovative pedagogical approaches, such as activity-based learning, inquiry-based learning, and problem-solving techniques, aimed at making STEM subjects more engaging and effective for students. CEMASTEA conducts rigorous applied research to evaluate the effectiveness of its training programs, identify best practices in STEM education, and generate evidence-based policy recommendations for the Ministry of Education and other stakeholders. The Centre organizes and hosts national and international conferences, workshops, and symposia, facilitating knowledge sharing, professional networking, and discussion of emerging trends in STEM education across Africa. It develops and disseminates a wide range of resource materials, including teacher manuals, student guides, and digital content, to support teachers in implementing effective STEM curricula. CEMASTEA offers advisory and consultancy services to educational institutions and governments on strategies for improving STEM education. It actively fosters collaborations with various local and international educational partners, non-governmental organizations, and government agencies to leverage resources and expertise. Furthermore, CEMASTEA serves as a key regional hub, acting as the Secretariat for the SMASE-Africa Network and ADEA's ICQN-MSE Network, coordinating STEM education initiatives, sharing best practices, and building capacity across African countries, thereby directly influencing the quality of STEM teaching and learning and contributing to the development of a scientifically and technologically literate workforce."

# Update metadata
process['metadata']['enrichment_method'] = "web_search_and_inference"
process['metadata']['confidence_level'] = "high (mandates, functions, legal basis from official website and other reliable sources) / medium (inferred responsibilities, narrative)"
process['metadata']['source_urls'] = [
    "https://www.cemastea.ac.ke/", # Official website
    "https://treasury.go.ke/", # Provided context
    "https://saraka.info/" # Provided context
]
process['metadata']['last_enriched_date'] = datetime.datetime.now().strftime("%Y-%m-%d")


# Save the updated JSON data
with open('combined_data.json', 'w') as f:
    json.dump(data, f, indent=2)

print("Hundred and fourth process enriched and combined_data.json updated.")
