# Generated by Django 4.2.16 on 2026-03-12 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_api', '0033_serviceconfig_service_api_config_24954e_gin_and_more'),
        ('document_repository', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtifactType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('metadata_schema', models.JSONField(blank=True, default=dict, help_text='JSON schema definition for required metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='artifact',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='mda_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='service_api.mda'),
        ),
        migrations.AddField(
            model_name='artifact',
            name='artifact_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='artifacts', to='document_repository.artifacttype'),
        ),
    ]
