# Generated by Django 4.2.16 on 2026-03-12 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document_repository', '0002_artifacttype_artifact_metadata_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artifact',
            name='category',
        ),
    ]
