# Generated by Django 4.2.16 on 2026-03-12 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_api', '0033_serviceconfig_service_api_config_24954e_gin_and_more'),
        ('document_repository', '0003_remove_artifact_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='NodeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Registry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mda_owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registries', to='service_api.mda')),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('full_path', models.CharField(db_index=True, max_length=1000, unique=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('node_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='document_repository.nodetype')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='document_repository.node')),
                ('registry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='document_repository.registry')),
            ],
            options={
                'unique_together': {('parent', 'slug')},
            },
        ),
        migrations.AddField(
            model_name='artifact',
            name='node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='document_repository.node'),
        ),
    ]
