# Generated by Django 4.2.16 on 2026-03-13 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_repository', '0004_nodetype_registry_node_artifact_node'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='node',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='artifact',
            name='is_public',
            field=models.BooleanField(default=False, help_text="If True, this artifact and its 'public' classified documents are visible on the public portal."),
        ),
    ]
