# Generated by Django 4.2.7 on 2026-03-13 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_api', '0033_serviceconfig_service_api_config_24954e_gin_and_more'),
        ('document_repository', '0005_alter_node_unique_together_artifact_is_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registry',
            name='mda_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registries', to='service_api.mda'),
        ),
    ]
