# Generated by Django 4.2.7 on 2026-03-13 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_repository', '0006_alter_registry_mda_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='submission_deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
