# Generated by Django 4.2.16 on 2026-03-16 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_repository', '0007_artifact_submission_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='extraction_confidence',
            field=models.FloatField(blank=True, help_text='Confidence score from OCR engine', null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='is_digitized',
            field=models.BooleanField(default=False, help_text='True if this document was digitized from a paper record'),
        ),
        migrations.AddField(
            model_name='document',
            name='needs_qa',
            field=models.BooleanField(default=False, help_text='Flags documents that require human-in-the-loop verification'),
        ),
        migrations.AddField(
            model_name='document',
            name='ocr_text',
            field=models.TextField(blank=True, help_text='Extracted text from intelligent document processing'),
        ),
    ]
