# Generated by Django 4.2.7 on 2025-12-28 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='is_escalated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('received', 'Received'), ('validation_failed', 'Validation Failed'), ('in_progress', 'In Progress'), ('escalated', 'Escalated'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('closed', 'Closed')], default='received', max_length=20),
        ),
    ]
