# Generated by Django 4.2.7 on 2025-12-28 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_api', '0002_servicerequest_is_escalated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflowstep',
            name='auto_process',
        ),
        migrations.AddField(
            model_name='workflowstep',
            name='api_config',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workflowstep',
            name='step_type',
            field=models.CharField(choices=[('manual', 'Manual'), ('api_call', 'API Call')], default='manual', max_length=20),
        ),
        migrations.AlterField(
            model_name='workflowstep',
            name='action',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='workflowstep',
            name='role',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
