# Generated by Django 4.2.7 on 2026-02-03 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_api', '0004_role_user_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='passport_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='saved_documents',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
