# Generated by Django 4.2.7 on 2026-02-03 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_api', '0006_mda_address_mda_code_mda_contact_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff', to='service_api.mda'),
        ),
    ]
