# Generated by Django 4.2.7 on 2026-02-04 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_api', '0007_user_mda'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowstep',
            name='target_mda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_steps', to='service_api.mda'),
        ),
    ]
