# Generated by Django 4.2.7 on 2026-02-05 03:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_api', '0008_workflowstep_target_mda'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('citizen', 'Citizen'), ('officer', 'Officer'), ('supervisor', 'Supervisor'), ('registrar', 'Registrar'), ('mda_admin', 'MDA Admin'), ('admin', 'Admin')], default='citizen', max_length=20),
        ),
    ]
