# Generated by Django 4.2.7 on 2026-02-10 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_api', '0009_servicerequest_assigned_to_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='serviceconfig',
            name='catalogue_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='serviceconfig',
            name='catalogue_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='serviceconfig',
            name='dependencies',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='serviceconfig',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceconfig',
            name='digitization_level',
            field=models.IntegerField(default=1, help_text='1=Manual, 5=Fully Digital'),
        ),
        migrations.AddField(
            model_name='serviceconfig',
            name='fees_applicable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='serviceconfig',
            name='is_public_facing',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='serviceconfig',
            name='legal_basis_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceconfig',
            name='life_event_group',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='serviceconfig',
            name='processing_time_estimate',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='serviceconfig',
            name='service_status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('deprecated', 'Deprecated'), ('draft', 'Draft')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='serviceconfig',
            name='shared_services',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='service_api.servicedomain')),
            ],
            options={
                'unique_together': {('name', 'domain')},
            },
        ),
        migrations.AddField(
            model_name='serviceconfig',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='service_api.servicecategory'),
        ),
    ]
