# Generated by Django 4.2.7 on 2026-02-10 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_api', '0010_servicedomain_serviceconfig_catalogue_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceconfig',
            name='blocking_issues',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceconfig',
            name='catalogue_tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='serviceconfig',
            name='consolidation_candidate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='serviceconfig',
            name='quick_wins',
            field=models.TextField(blank=True, null=True),
        ),
    ]
