# Generated by Django 4.2.7 on 2026-02-10 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_api', '0011_serviceconfig_blocking_issues_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceconfig',
            name='associated_actors',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='serviceconfig',
            name='associated_systems',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
