# Generated by Django 4.2.7 on 2026-02-10 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_api', '0012_serviceconfig_associated_actors_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterDepartmentalMemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_read', models.BooleanField(default=False)),
                ('recipient_mda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbound_memos', to='service_api.mda')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_memos', to=settings.AUTH_USER_MODEL)),
                ('sender_mda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbound_memos', to='service_api.mda')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
