# Generated by Django 4.2.7 on 2026-02-10 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_api', '0013_interdepartmentalmemo'),
    ]

    operations = [
        migrations.CreateModel(
            name='GovernmentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_number', models.CharField(max_length=100, unique=True)),
                ('subject', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('open', 'Open'), ('pending', 'Pending'), ('escalated', 'Escalated'), ('closed', 'Closed'), ('archived', 'Archived')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owning_mda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registry_files', to='service_api.mda')),
            ],
        ),
        migrations.AddField(
            model_name='interdepartmentalmemo',
            name='digitally_signed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='interdepartmentalmemo',
            name='memo_type',
            field=models.CharField(choices=[('policy', 'Policy Memo'), ('operational', 'Operational Request'), ('instruction', 'Instruction'), ('concurrence', 'Concurrence'), ('escalation', 'Escalation'), ('information', 'Information')], default='operational', max_length=30),
        ),
        migrations.AddField(
            model_name='interdepartmentalmemo',
            name='official_ref',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='interdepartmentalmemo',
            name='parent_memo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responses', to='service_api.interdepartmentalmemo'),
        ),
        migrations.AddField(
            model_name='interdepartmentalmemo',
            name='signed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signed_memos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='interdepartmentalmemo',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft (Initiated)'), ('internal_approval', 'Pending Internal Approval'), ('registered', 'Registry Registered'), ('actioning', 'In Action'), ('responded', 'Responded'), ('closed', 'Closed')], default='draft', max_length=30),
        ),
        migrations.CreateModel(
            name='OfficialLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('official_ref', models.CharField(max_length=100, unique=True)),
                ('recipient_name', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gov_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='letters', to='service_api.governmentfile')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CorrespondenceAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruction', models.TextField()),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('progress_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('memo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='service_api.interdepartmentalmemo')),
            ],
        ),
        migrations.AddField(
            model_name='interdepartmentalmemo',
            name='gov_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memos', to='service_api.governmentfile'),
        ),
    ]
