# Generated by Django 4.2.7 on 2026-02-11 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_api', '0014_governmentfile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowstep',
            name='bpmn_element_type',
            field=models.CharField(choices=[('start_event', 'Start Event'), ('user_task', 'User Task'), ('service_task', 'Service Task'), ('exclusive_gateway', 'Exclusive Gateway'), ('end_event', 'End Event')], default='user_task', max_length=30),
        ),
        migrations.AlterField(
            model_name='interdepartmentalmemo',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft (Initiated)'), ('reviewing', 'In Internal Review'), ('approved', 'Internally Approved'), ('registered', 'Registry Registered'), ('signed', 'Digitally Signed'), ('actioning', 'Issued & In Action'), ('responded', 'Responded'), ('closed', 'Closed')], default='draft', max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('citizen', 'Citizen'), ('officer', 'Officer'), ('supervisor', 'Supervisor'), ('registrar', 'Registrar'), ('mda_admin', 'MDA Admin'), ('system_admin', 'System Admin'), ('admin', 'Admin')], default='citizen', max_length=20),
        ),
    ]
