# Generated by Django 4.2.7 on 2026-02-11 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_api', '0015_workflowstep_bpmn_element_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowstep',
            name='lifecycle_stage',
            field=models.CharField(choices=[('as_is', 'As-Is (Current)'), ('to_be', 'To-Be (Optimized)')], default='as_is', max_length=10),
        ),
    ]
