# Generated by Django 4.2.16 on 2026-02-12 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_api', '0016_workflowstep_lifecycle_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceconfig',
            name='delivery_channels',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='serviceconfig',
            name='pain_points',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='serviceconfig',
            name='process_complexity',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='serviceconfig',
            name='service_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='serviceconfig',
            name='config',
            field=models.JSONField(default=dict),
        ),
    ]
