# Generated by Django 4.2.7 on 2026-02-12 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_api', '0017_serviceconfig_delivery_channels_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceconfig',
            name='form_schema',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
