# Generated by Django 4.2.16 on 2026-02-13 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_api', '0018_serviceconfig_form_schema'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='actor_mdas',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='actor_role',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='decision',
            field=models.CharField(choices=[('ALLOW', 'ALLOW'), ('DENY', 'DENY')], default='ALLOW', max_length=10),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='owning_mda_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='process_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='service_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='assigned_mdas',
            field=models.ManyToManyField(blank=True, related_name='assigned_users', to='service_api.mda'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='service_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='service_api.servicerequest'),
        ),
    ]
