# Generated by Django 4.2.7 on 2026-02-14 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_api', '0019_auditlog_actor_mdas_auditlog_actor_role_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesktopReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_id', models.CharField(blank=True, max_length=100, null=True)),
                ('executive_summary', models.TextField(blank=True, null=True)),
                ('process_overview', models.JSONField(blank=True, default=dict)),
                ('stakeholders', models.JSONField(blank=True, default=list)),
                ('inputs_outputs_dependencies', models.JSONField(blank=True, default=dict)),
                ('process_maturity', models.JSONField(blank=True, default=dict)),
                ('as_is_narrative', models.TextField(blank=True, null=True)),
                ('as_is_steps', models.JSONField(blank=True, default=list)),
                ('pain_points_bottlenecks_risks', models.JSONField(blank=True, default=list)),
                ('to_be_process', models.JSONField(blank=True, default=dict)),
                ('digitization_opportunities', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desktop_reviews', to='service_api.mda')),
            ],
        ),
    ]
