# Generated by Django 4.2.16 on 2026-02-17 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_api', '0021_serviceconfig_priority_servicerequest_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistryAdapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique code (e.g., IPRS, KRA, CRS)', max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('base_url', models.URLField(blank=True, help_text='Authoritative API Base URL', null=True)),
                ('auth_config', models.JSONField(blank=True, default=dict, help_text='Headers, API Keys, or Certificates')),
                ('data_mapping', models.JSONField(blank=True, default=dict, help_text='Field mapping from Registry -> Platform')),
                ('is_mock', models.BooleanField(default=True)),
                ('mock_data', models.JSONField(blank=True, default=dict, help_text='JSON dump of original authoritative dictionaries')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
