# Generated by Django 4.2.16 on 2026-02-19 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_api', '0024_datapurpose_consentrecord_consentaccesslog'),
    ]

    operations = [
        migrations.AddField(
            model_name='registryadapter',
            name='auth_type',
            field=models.CharField(default='API_KEY', help_text='API_KEY, OAUTH2, CERTIFICATE, etc.', max_length=50),
        ),
        migrations.CreateModel(
            name='RegistryEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Human-readable action name', max_length=255)),
                ('path', models.CharField(help_text='Endpoint path (e.g., /api/births)', max_length=255)),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE')], default='POST', max_length=10)),
                ('payload_schema', models.JSONField(blank=True, default=dict, help_text='JSON Schema for the expected payload')),
                ('adapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endpoints', to='service_api.registryadapter')),
            ],
        ),
        migrations.AddField(
            model_name='workflowstep',
            name='registry_endpoint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configured_steps', to='service_api.registryendpoint'),
        ),
    ]
