# Generated by Django 4.2.16 on 2026-02-19 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_api', '0025_registryadapter_auth_type_registryendpoint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registryendpoint',
            name='input_schema',
            field=models.JSONField(blank=True, default=list, help_text="List of required inputs: [{'key': 'id', 'label': 'ID', 'type': 'string'}]"),
        ),
        migrations.AddField(
            model_name='registryendpoint',
            name='output_schema',
            field=models.JSONField(blank=True, default=list, help_text="List of available outputs: [{'key': 'name', 'label': 'Name', 'type': 'string'}]"),
        ),
    ]
