# Generated by Django 4.2.16 on 2026-02-20 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_api', '0026_registryendpoint_input_schema_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowstep',
            name='logic_config',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
