# Generated by Django 4.2.16 on 2026-03-03 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_api', '0027_workflowstep_logic_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('shared_workflow_template', models.JSONField(blank=True, help_text='Template for workflow steps shared by all services in this family.', null=True)),
                ('shared_form_schema', models.JSONField(blank=True, help_text='Default form schema fields shared by all services in this family.', null=True)),
            ],
            options={
                'verbose_name_plural': 'Service Families',
            },
        ),
        migrations.AlterField(
            model_name='serviceconfig',
            name='mda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='service_api.mda'),
        ),
        migrations.AddField(
            model_name='serviceconfig',
            name='service_family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='service_api.servicefamily'),
        ),
    ]
