# Generated by Django 4.2.7 on 2026-03-05 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_api', '0028_servicefamily_alter_serviceconfig_mda_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Service Groups',
            },
        ),
        migrations.AddField(
            model_name='serviceconfig',
            name='service_groups',
            field=models.ManyToManyField(blank=True, related_name='services', to='service_api.servicegroup'),
        ),
    ]
