# Generated by Django 4.2.7 on 2026-03-05 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_api', '0029_servicegroup_serviceconfig_service_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='mda',
            name='is_priority',
            field=models.BooleanField(default=False),
        ),
    ]
