# Generated by Django 4.2.7 on 2026-03-05 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_api', '0030_mda_is_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('citizen', 'Citizen'), ('officer', 'Officer'), ('supervisor', 'Supervisor'), ('registrar', 'Registrar'), ('mda_admin', 'MDA Admin'), ('system_admin', 'System Admin'), ('admin', 'Admin'), ('GLOBAL_OFFICER', 'Global Officer'), ('GLOBAL_SUPERVISOR', 'Global Supervisor'), ('MDA_OFFICER', 'MDA Officer'), ('MDA_SUPERVISOR', 'MDA Supervisor'), ('employee', 'Employee'), ('Hospital_Staff', 'Hospital Staff')], default='citizen', max_length=20),
        ),
    ]
