# Generated by Django 4.2.16 on 2026-03-12 10:38

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_api', '0032_servicerequest_completed_at_workflowstepexecution'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='serviceconfig',
            index=django.contrib.postgres.indexes.GinIndex(fields=['config'], name='service_api_config_24954e_gin'),
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=django.contrib.postgres.indexes.GinIndex(fields=['payload'], name='service_api_payload_3a8298_gin'),
        ),
    ]
