version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: ./docker/prod/backend/Dockerfile
    entrypoint: ["/app/entry.sh"]
    command: gunicorn project.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/app/staticfiles
    env_file:
      - .env
    depends_on:
      - db
      - redis
    restart: always

  nginx:
    build:
      context: .
      dockerfile: ./docker/prod/nginx/Dockerfile
    volumes:
      - static_volume:/app/staticfiles
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  redis:
    image: redis:7-alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

volumes:
  postgres_data:
  static_volume:
