import os
import django

# Set up Django environment
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'project.settings')
django.setup()

from service_api.models import MDA, ServiceConfig, WorkflowStep, ServiceCategory, ServiceDomain, ServiceFamily, ServiceGroup, User
from django.db import transaction

@transaction.atomic
def seed_batch_3():
    def get_taxonomy(domain_name, category_name, family_name, group_name):
        domain, _ = ServiceDomain.objects.get_or_create(name=domain_name)
        category, _ = ServiceCategory.objects.get_or_create(name=category_name, domain=domain)
        family, _ = ServiceFamily.objects.get_or_create(name=family_name)
        group, _ = ServiceGroup.objects.get_or_create(name=group_name)
        return category, family, group

    # 1. NACOSTI
    mda_nacosti, _ = MDA.objects.update_or_create(code="NACOSTI", defaults={'name': "National Commission for Science, Technology and Innovation", 'is_priority': True})
    cat, fam, grp = get_taxonomy("Economic & Regulatory", "Research Licensing", "Education & Research", "Employment & Business")
    service_nacosti, _ = ServiceConfig.objects.update_or_create(service_code="NAC-LIC-001", defaults={'service_name': "Research Licensing & Knowledge Management", 'description': "Automated research vetting and national repository sync.", 'mda': mda_nacosti, 'category': cat, 'service_family': fam, 'service_type': 'G2B', 'is_public_facing': True, 'form_schema': {"fields": [{"name": "research_title", "label": "Research Title", "type": "text", "required": True}, {"name": "institution", "label": "Affiliated Institution", "type": "text", "required": True}, {"name": "ethics_cert", "label": "Ethical Clearance Reference", "type": "text", "required": True}]}})
    service_nacosti.service_groups.add(grp)
    WorkflowStep.objects.filter(service_config=service_nacosti).delete()
    for s in [{'sequence': 10, 'step_name': "Verify Academic Standing (KNQA)", 'step_type': 'api_call', 'bpmn_element_type': 'service_task', 'role': 'system', 'api_config': {'url': 'HUDUMA_BRIDGE/KNQA/verify', 'outcomes': [{'label': 'verified', 'target_sequence': 20}, {'label': 'fail', 'target_sequence': 11}]}}, {'sequence': 11, 'step_name': "[Fallback] Manual Credential Review", 'step_type': 'manual', 'bpmn_element_type': 'user_task', 'role': 'NACOSTI_OFFICER', 'api_config': {'outcomes': [{'label': 'verified', 'target_sequence': 20}]}}, {'sequence': 20, 'step_name': "Cross-check Ethical Clearance (ERC)", 'step_type': 'api_call', 'bpmn_element_type': 'service_task', 'role': 'system', 'api_config': {'url': 'HUDUMA_BRIDGE/ERC/check'}}, {'sequence': 30, 'step_name': "Initiate Payment via GPA", 'step_type': 'api_call', 'bpmn_element_type': 'service_task', 'role': 'system', 'api_config': {'url': 'HUDUMA_BRIDGE/GPA/collect'}}, {'sequence': 40, 'step_name': "Generate Verifiable Digital License", 'step_type': 'api_call', 'bpmn_element_type': 'service_task', 'role': 'system', 'api_config': {'url': 'internal://output/gen_license'}}, {'sequence': 50, 'step_name': "Sync to National Research Repository", 'step_type': 'api_call', 'bpmn_element_type': 'service_task', 'role': 'system', 'api_config': {'url': 'internal://knowledge/sync'}}]: WorkflowStep.objects.create(service_config=service_nacosti, lifecycle_stage='to_be', **s)

    # 2 & 3. OHPS / Presidency Directives
    mda_pres, _ = MDA.objects.update_or_create(code="PRESIDENCY", defaults={'name': "Executive Office of the President", 'is_priority': True})
    cat, fam, grp = get_taxonomy("Policy & Governance", "Executive Coordination", "Governance & Policy", "Social Protection & Justice")
    service_dir, _ = ServiceConfig.objects.update_or_create(service_code="PRE-DIR-001", defaults={'service_name': "Presidential Directives Management", 'description': "Real-time tracking of national priority projects.", 'mda': mda_pres, 'category': cat, 'service_family': fam, 'service_type': 'G2G', 'is_public_facing': False, 'form_schema': {"fields": [{"name": "directive_title", "label": "Directive Title", "type": "text", "required": True}, {"name": "lead_mda", "label": "Lead MDA", "type": "text", "required": True}, {"name": "deadline", "label": "Implementation Deadline", "type": "date", "required": True}]}})
    service_dir.service_groups.add(grp)
    WorkflowStep.objects.filter(service_config=service_dir).delete()
    for s in [{'sequence': 10, 'step_name': "Secure Storage in National Registry", 'step_type': 'api_call', 'bpmn_element_type': 'service_task', 'role': 'system', 'api_config': {'url': 'internal://registry/store_directive'}}, {'sequence': 20, 'step_name': "Automated Task Assignment to PSs", 'step_type': 'api_call', 'bpmn_element_type': 'service_task', 'role': 'system', 'api_config': {'url': 'internal://workflow/auto_assign'}}, {'sequence': 30, 'step_name': "Submit Digital Milestone Update", 'step_type': 'manual', 'bpmn_element_type': 'user_task', 'role': 'PRINCIPAL_SECRETARY'}, {'sequence': 40, 'step_name': "Real-time Compliance Fetch (X-Road)", 'step_type': 'api_call', 'bpmn_element_type': 'service_task', 'role': 'system', 'api_config': {'url': 'HUDUMA_BRIDGE/MDAS/fetch_kpis'}}, {'sequence': 50, 'step_name': "Generate Strategic Situational Report", 'step_type': 'manual', 'bpmn_element_type': 'user_task', 'role': 'HEAD_OF_PUBLIC_SERVICE'}]: WorkflowStep.objects.create(service_config=service_dir, lifecycle_stage='to_be', **s)

    # 4. Correctional Services
    mda_corr, _ = MDA.objects.update_or_create(code="CORRECTIONAL", defaults={'name': "State Department for Correctional Services", 'is_priority': True})
    cat, fam, grp = get_taxonomy("Policy & Governance", "Inmate Management", "Justice & Security", "Social Protection & Justice")
    service_corr, _ = ServiceConfig.objects.update_or_create(service_code="COR-CAS-001", defaults={'service_name': "Inmate Case & Rehabilitation Management", 'description': "Digital inmate profiling and rehabilitation tracking.", 'mda': mda_corr, 'category': cat, 'service_family': fam, 'service_type': 'G2G', 'is_public_facing': False, 'form_schema': {"fields": [{"name": "warrant_no", "label": "Committal Warrant Number", "type": "text", "required": True}, {"name": "inmate_maisha", "label": "Inmate Maisha Namba", "type": "text", "required": True}]}})
    service_corr.service_groups.add(grp)
    WorkflowStep.objects.filter(service_config=service_corr).delete()
    for s in [{'sequence': 10, 'step_name': "Receive Digital Court Warrant", 'step_type': 'manual', 'bpmn_element_type': 'user_task', 'role': 'PRISON_RECEPTION_OFFICER'}, {'sequence': 20, 'step_name': "Biometric Identity Verification (IPRS)", 'step_type': 'api_call', 'bpmn_element_type': 'service_task', 'role': 'system', 'api_config': {'url': 'HUDUMA_BRIDGE/IPRS/verify_bio'}}, {'sequence': 30, 'step_name': "Create Digital Inmate Profile", 'step_type': 'api_call', 'bpmn_element_type': 'service_task', 'role': 'system', 'api_config': {'url': 'internal://prison/create_profile'}}, {'sequence': 40, 'step_name': "Track Rehabilitation & Education", 'step_type': 'manual', 'bpmn_element_type': 'user_task', 'role': 'WELFARE_OFFICER'}, {'sequence': 50, 'step_name': "Auto-calculate Sentence Expiry", 'step_type': 'api_call', 'bpmn_element_type': 'service_task', 'role': 'system', 'api_config': {'url': 'internal://prison/calc_expiry'}}, {'sequence': 60, 'step_name': "Execute Digital Release & Update Registry", 'step_type': 'api_call', 'bpmn_element_type': 'service_task', 'role': 'system', 'api_config': {'url': 'internal://prison/release'}}]: WorkflowStep.objects.create(service_config=service_corr, lifecycle_stage='to_be', **s)

    # 5. Immigration (Passport)
    mda_imm, _ = MDA.objects.update_or_create(code="IMMIGRATION", defaults={'name': "Directorate of Immigration Services", 'is_priority': True})
    cat, fam, grp = get_taxonomy("Social & Citizen Services", "Travel Documents", "Identity & Travel", "Identity & Travel")
    service_pass, _ = ServiceConfig.objects.update_or_create(service_code="IMM-PAS-001", defaults={'service_name': "Passport Application & Issuance", 'description': "Digital passport issuance with biometric reuse for renewals.", 'mda': mda_imm, 'category': cat, 'service_family': fam, 'service_type': 'G2C', 'is_public_facing': True, 'form_schema': {"fields": [{"name": "passport_type", "label": "Passport Type", "type": "select", "options": ["Ordinary", "Diplomatic", "Service"], "required": True}, {"name": "maisha_namba", "label": "Maisha Namba", "type": "text", "required": True}, {"name": "delivery_address", "label": "Delivery Address", "type": "text", "required": True}]}})
    service_pass.service_groups.add(grp)
    WorkflowStep.objects.filter(service_config=service_pass).delete()
    for s in [{'sequence': 10, 'step_name': "Verify Identity via National Registry", 'step_type': 'api_call', 'bpmn_element_type': 'service_task', 'role': 'system', 'api_config': {'url': 'HUDUMA_BRIDGE/IPRS/verify', 'outcomes': [{'label': 'verified', 'target_sequence': 20}, {'label': 'fail', 'target_sequence': 11}]}}, {'sequence': 11, 'step_name': "[Fallback] Physical ID Verification", 'step_type': 'manual', 'bpmn_element_type': 'user_task', 'role': 'IMMIGRATION_OFFICER', 'api_config': {'outcomes': [{'label': 'verified', 'target_sequence': 20}]}}, {'sequence': 20, 'step_name': "Determine Biometric Requirement", 'step_type': 'api_call', 'bpmn_element_type': 'service_task', 'role': 'system', 'api_config': {'url': 'internal://imm/check_bio', 'outcomes': [{'label': 'capture_needed', 'target_sequence': 30}, {'label': 'reuse_bio', 'target_sequence': 40}]}}, {'sequence': 30, 'step_name': "Biometric Enrollment", 'step_type': 'manual', 'bpmn_element_type': 'user_task', 'role': 'IMMIGRATION_ENROLLER', 'api_config': {'outcomes': [{'label': 'captured', 'target_sequence': 40}]}}, {'sequence': 40, 'step_name': "Decentralized Automated Printing", 'step_type': 'api_call', 'bpmn_element_type': 'service_task', 'role': 'system', 'api_config': {'url': 'internal://output/print_passport'}}, {'sequence': 50, 'step_name': "Secure Courier Dispatch (Posta)", 'step_type': 'api_call', 'bpmn_element_type': 'service_task', 'role': 'system', 'api_config': {'url': 'HUDUMA_BRIDGE/LOGISTICS/dispatch'}}]: WorkflowStep.objects.create(service_config=service_pass, lifecycle_stage='to_be', **s)

    # 6. Sports
    mda_sports, _ = MDA.objects.update_or_create(code="SPORTS", defaults={'name': "State Department for Sports", 'is_priority': True})
    cat, fam, grp = get_taxonomy("Social & Citizen Services", "Sports Management", "Arts & Culture", "Employment & Business")
    service_sports, _ = ServiceConfig.objects.update_or_create(service_code="SPR-MGT-001", defaults={'service_name': "Athlete Grants & Facility Booking", 'description': "Unified sports portal for grants and stadium bookings.", 'mda': mda_sports, 'category': cat, 'service_family': fam, 'service_type': 'G2C', 'is_public_facing': True, 'form_schema': {"fields": [{"name": "maisha_namba", "label": "Athlete Maisha Namba", "type": "text", "required": True}, {"name": "facility", "label": "Select Facility", "type": "select", "options": ["Kasarani", "Nyayo", "Kipchoge Keino"], "required": False}, {"name": "grant_purpose", "label": "Grant Purpose", "type": "text", "required": False}]}})
    service_sports.service_groups.add(grp)
    WorkflowStep.objects.filter(service_config=service_sports).delete()
    for s in [{'sequence': 10, 'step_name': "Verify Athlete via IPRS/NEMIS", 'step_type': 'api_call', 'bpmn_element_type': 'service_task', 'role': 'system', 'api_config': {'url': 'HUDUMA_BRIDGE/ATHLETE/verify'}}, {'sequence': 20, 'step_name': "Facility Availability & Booking", 'step_type': 'api_call', 'bpmn_element_type': 'service_task', 'role': 'system', 'api_config': {'url': 'internal://sports/check_availability'}}, {'sequence': 30, 'step_name': "Disburse Grant via Digital Wallet", 'step_type': 'api_call', 'bpmn_element_type': 'service_task', 'role': 'system', 'api_config': {'url': 'HUDUMA_BRIDGE/GPA/disburse_grant'}}, {'sequence': 40, 'step_name': "Issue Digital Access Ticket (QR)", 'step_type': 'api_call', 'bpmn_element_type': 'service_task', 'role': 'system', 'api_config': {'url': 'internal://output/gen_ticket'}}]: WorkflowStep.objects.create(service_config=service_sports, lifecycle_stage='to_be', **s)

    # 7. Special Programmes
    mda_social, _ = MDA.objects.update_or_create(code="SOCIAL_PROTECTION", defaults={'name': "State Department for Special Programmes", 'is_priority': True})
    cat, fam, grp = get_taxonomy("Social & Citizen Services", "Social Protection", "Social Protection", "Social Protection & Justice")
    service_social, _ = ServiceConfig.objects.update_or_create(service_code="SOC-PRO-001", defaults={'service_name': "Social Protection & Beneficiary Management", 'description': "Biometric-linked social safety net disbursements.", 'mda': mda_social, 'category': cat, 'service_family': fam, 'service_type': 'G2C', 'is_public_facing': True, 'form_schema': {"fields": [{"name": "maisha_namba", "label": "Maisha Namba", "type": "text", "required": True}, {"name": "household_size", "label": "Household Size", "type": "number", "required": True}, {"name": "location", "label": "Current Location (Sub-County)", "type": "text", "required": True}]}})
    service_social.service_groups.add(grp)
    WorkflowStep.objects.filter(service_config=service_social).delete()
    for s in [{'sequence': 10, 'step_name': "Biometric Identity Verification", 'step_type': 'api_call', 'bpmn_element_type': 'service_task', 'role': 'system', 'api_config': {'url': 'HUDUMA_BRIDGE/IPRS/verify_bio'}}, {'sequence': 20, 'step_name': "Fetch Household Data (Social Registry)", 'step_type': 'api_call', 'bpmn_element_type': 'service_task', 'role': 'system', 'api_config': {'url': 'HUDUMA_BRIDGE/CSR/fetch'}}, {'sequence': 30, 'step_name': "AI Eligibility Scoring (Means Test)", 'step_type': 'api_call', 'bpmn_element_type': 'service_task', 'role': 'system', 'api_config': {'url': 'internal://social/score'}}, {'sequence': 40, 'step_name': "Digital Enrollment & GPA Trigger", 'step_type': 'api_call', 'bpmn_element_type': 'service_task', 'role': 'system', 'api_config': {'url': 'HUDUMA_BRIDGE/GPA/disburse_benefit'}}]: WorkflowStep.objects.create(service_config=service_social, lifecycle_stage='to_be', **s)

    # 8. ICT Policy Coordination
    mda_ictp, _ = MDA.objects.update_or_create(code="ICT_POLICY", defaults={'name': "State Department for ICT and the Digital Economy", 'is_priority': True})
    cat, fam, grp = get_taxonomy("Policy & Governance", "Digital Policy", "Technology & Innovation", "Social Protection & Justice")
    service_ictp, _ = ServiceConfig.objects.update_or_create(service_code="ICT-POL-001", defaults={'service_name': "Digital Government Policy Coordination", 'description': "Standardizing whole-of-government digital transformation.", 'mda': mda_ictp, 'category': cat, 'service_family': fam, 'service_type': 'G2G', 'is_public_facing': False, 'form_schema': {"fields": [{"name": "mda_id", "label": "Target MDA", "type": "text", "required": True}, {"name": "ge_compliance", "label": "GEA Compliance Report", "type": "file", "required": True}]}})
    service_ictp.service_groups.add(grp)
    WorkflowStep.objects.filter(service_config=service_ictp).delete()
    for s in [{'sequence': 10, 'step_name': "GEA Architecture Review", 'step_type': 'manual', 'bpmn_element_type': 'user_task', 'role': 'ICT_POLICY_ANALYST'}, {'sequence': 20, 'step_name': "Integrate via KeSEL (X-Road)", 'step_type': 'api_call', 'bpmn_element_type': 'service_task', 'role': 'system', 'api_config': {'url': 'HUDUMA_BRIDGE/KESEL/register'}}, {'sequence': 30, 'step_name': "Apply NPKI & Security Trust Controls", 'step_type': 'api_call', 'bpmn_element_type': 'service_task', 'role': 'system', 'api_config': {'url': 'internal://trust/apply_controls'}}]: WorkflowStep.objects.create(service_config=service_ictp, lifecycle_stage='to_be', **s)

    # 9. Youth Affairs
    mda_youth, _ = MDA.objects.update_or_create(code="YOUTH", defaults={'name': "State Department for Youth Affairs", 'is_priority': True})
    cat, fam, grp = get_taxonomy("Social & Citizen Services", "Youth Empowerment", "Education & Research", "Employment & Business")
    service_youth, _ = ServiceConfig.objects.update_or_create(service_code="YOU-EMP-001", defaults={'service_name': "Youth Internship & AGPO Certification", 'description': "Automated internship matching and instant AGPO issuance.", 'mda': mda_youth, 'category': cat, 'service_family': fam, 'service_type': 'G2C', 'is_public_facing': True, 'form_schema': {"fields": [{"name": "maisha_namba", "label": "Maisha Namba", "type": "text", "required": True}, {"name": "business_no", "label": "BRS Business Number (for AGPO)", "type": "text", "required": False}, {"name": "skills", "label": "Primary Skills", "type": "text", "required": True}]}})
    service_youth.service_groups.add(grp)
    WorkflowStep.objects.filter(service_config=service_youth).delete()
    for s in [{'sequence': 10, 'step_name': "Auto-fetch Profile (IPRS/KNQA/BRS)", 'step_type': 'api_call', 'bpmn_element_type': 'service_task', 'role': 'system', 'api_config': {'url': 'HUDUMA_BRIDGE/YOUTH/verify_all'}}, {'sequence': 20, 'step_name': "AI Skill & Location Match (Internship)", 'step_type': 'api_call', 'bpmn_element_type': 'service_task', 'role': 'system', 'api_config': {'url': 'internal://youth/match'}}, {'sequence': 30, 'step_name': "Automated Ownership & Age Validation (AGPO)", 'step_type': 'api_call', 'bpmn_element_type': 'service_task', 'role': 'system', 'api_config': {'url': 'internal://youth/verify_agpo'}}, {'sequence': 40, 'step_name': "Generate Verifiable Digital Certification", 'step_type': 'api_call', 'bpmn_element_type': 'service_task', 'role': 'system', 'api_config': {'url': 'internal://output/gen_cert'}}]: WorkflowStep.objects.create(service_config=service_youth, lifecycle_stage='to_be', **s)

    # 10. Refugee Services
    mda_ref, _ = MDA.objects.update_or_create(code="REFUGEE", defaults={'name': "Department of Refugee Services", 'is_priority': True})
    cat, fam, grp = get_taxonomy("Social & Citizen Services", "Refugee Documentation", "Identity & Travel", "Identity & Travel")
    service_ref, _ = ServiceConfig.objects.update_or_create(service_code="REF-DOC-001", defaults={'service_name': "Refugee Status Determination & IDs", 'description': "Biometric refugee registration and Maisha Namba minting.", 'mda': mda_ref, 'category': cat, 'service_family': fam, 'service_type': 'G2C', 'is_public_facing': True, 'form_schema': {"fields": [{"name": "origin_country", "label": "Country of Origin", "type": "text", "required": True}, {"name": "entry_point", "label": "Point of Entry", "type": "text", "required": True}]}})
    service_ref.service_groups.add(grp)
    WorkflowStep.objects.filter(service_config=service_ref).delete()
    for s in [{'sequence': 10, 'step_name': "Biometric Intake & X-Road Cross-check", 'step_type': 'manual', 'bpmn_element_type': 'user_task', 'role': 'REFUGEE_REGISTRATION_OFFICER'}, {'sequence': 20, 'step_name': "Digital RSD Committee Approval", 'step_type': 'manual', 'bpmn_element_type': 'user_task', 'role': 'RSD_COMMITTEE_MEMBER'}, {'sequence': 30, 'step_name': "Mint Refugee Maisha Namba (IPRS)", 'step_type': 'api_call', 'bpmn_element_type': 'service_task', 'role': 'system', 'api_config': {'url': 'HUDUMA_BRIDGE/IPRS/mint_refugee'}}, {'sequence': 40, 'step_name': "Auto-trigger ID & Travel Doc Printing", 'step_type': 'api_call', 'bpmn_element_type': 'service_task', 'role': 'system', 'api_config': {'url': 'internal://output/print_ref_id'}}]: WorkflowStep.objects.create(service_config=service_ref, lifecycle_stage='to_be', **s)

    print("Successfully seeded Batch 3 (10 MDAs)")

if __name__ == "__main__":
    seed_batch_3()
